### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error

### ISSUE THREAD

**Issue by PappyEric** [superdesk/superdesk-wordpress-plugin#3]
With two fresh WP installations I get the following error upon activating the plugin:

Parse error: syntax error, unexpected '[' in /home/content/29/11307329/html/elmnewspapernorth/wp-content/plugins/superdesk-wordpress-plugin-master/superdeskPublisher.php on line 89

This is my first attempt at using the Superdesk --> Wordpress plugin so let me know if I'm missing something simple in the instructions. Wordpress versio 4.7.4 using the default TWENTY SEVENTEEN theme.

**Comment by SourceDouglas** [comment]
Hi, have you downloaded the plugin as a .zip from the Github? We haven't seen this error before. 

Maybe you could describe the steps you've taken?

**Comment by PappyEric** [comment]
Thanks for the quick response.

Yes, I downloaded the zip from Github and using the directions as described here:
https://wiki.sourcefabric.org/display/NR/How+to+install+and+set+up+the+Wordpress+Superdesk+Plugin

I have now tried on three different WP sites two of which were new installations on subdomains (default themes) and one just now on an established site on a main domain. I use GoDaddy to host these sites.

The error occurs directly after clicking the "activate plugin" upon .zip upload.

**Comment by PappyEric** [comment]
Update!

I installed a fresh site on WPEngine and it activated perfectly.
I'm going to create an instance on Linode too and see what happens there.

I don't know if this latest news helps you but it seems like GoDaddy doesn't like the plugin.

**Comment by SourceDouglas** [comment]
Thanks for that info. I suspect GoDaddy is doing something with their database.

Do you have Superdesk installed? Were you able to get that installed OK?

**Comment by SourceDouglas** [comment]
I've updated the wiki with the info that you've provided here. Thanks for that!

**Comment by PappyEric** [comment]
Yes, Superdesk is installed and working on a Linode virtual machine.

Now! Let's get down to business!

Thanks for your fast responses to my issues. The hope on our end is to consolidate the editing and publishing desks of several small struggling rural newspapers here in West Virginia , USA. We're working on scripts to export the Wordpress sites via XML to Adobe Indesign for print purposes and have a clearing house of articles on Superdesk allowing editors and publishers to push them out to the Wordpress sites.

We are working with a foundation to assist new journalists that want to help rural community newspapers revitalize their digital presence while also catering to the print media customers they already have.

I hope this keeps moving forward and we'll keep you posted on our progress!

**Comment by SourceDouglas** [comment]
Wonderful! Please keep me posted and feel free to write to the Superdesk developers' forum at https://forum.sourcefabric.org/categories/superdesk-dev. 

As for the Indesign method, please let us know how you're achieving that; not sure if it will help, but Superdesk can also export articles in the NewsML XML format.

**Comment by SourceDouglas** [comment]
We've updated the plugin to work with shared WP instances. We've tested it and it works now. Please reopen if there's something that doesn't work.
