### ISSUE TITLE
Publish to Wordpress failed

### ISSUE THREAD

**Issue by PappyEric** [superdesk/superdesk-wordpress-plugin#4]
Getting this error when publishing an article to Wordpress:

PublishHTTPPushClientError Error 14001 - HTTP push publish client error:Error pushing item 403

I've stepped through at least four times the "How to install and set up the Wordpress Superdesk Plugin" but I'm not getting anywhere. I'm probably just tired after this 14hr day and will completely get it together tomorrow!

Regardless - I'm falling in love with the power that I can see in Superdesk and I know  (with help from you folks here) I'll get this figured out.

Thanks!

**Comment by SourceDouglas** [comment]
Were you able to resolve this one, or is it something we need to look at? Personally I haven't seen any of these errors. Is that on the WP side?
